apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bodhi-external-postgresql-public
  namespace: postgresql 
spec:
  interval: 5m0s
  timeout: 30s
  chart:
    spec:
      chart: postgresql
      version: 15.5.32
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    auth:
      username: bodhiint
      password: bodhiint
      database: app
    primary:
      service:
        type: LoadBalancer 
        port: 15232          
      persistence:
        existingClaim: bodhi-postgresql-ebs-claim  
      resources:
        requests:
          cpu: 100m
          memory: 300Mi
        limits:
          cpu: 200m
          memory: 600Mi
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-group  
                    operator: In
                    values:
                      - int       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bodhi-postgresql-ebs-claim
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 4Gi