apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bodhi-eks-admin
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/DavidGoodman2333/bodhi-eks-admin.git
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/int
  prune: true
  sourceRef:
    kind: GitRepository
    name: bodhi-eks-admin