apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/int
  prune: true
  sourceRef:
    kind: GitRepository
    name: bodhi-eks-admin